# Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate the standalone reusable MBridge workflow."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE_PATH = ROOT / ".github/scripts/mbridge_orchestrator.py"
WORKFLOW_PATH = ROOT / ".github/workflows/_mbridge_orchestrator.yml"


def render_workflow(source: str) -> str:
    indented_source = "\n".join(
        f"          {line}" if line else "" for line in source.rstrip().splitlines()
    )
    return f"""# Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# GENERATED by .github/scripts/generate_mbridge_workflow.py.
# Edit .github/scripts/mbridge_orchestrator.py and regenerate this file.

name: Run MBridge validation

on:
  workflow_call:
    inputs:
      mcore_ref:
        description: Full Megatron-LM commit SHA tested by MBridge
        required: true
        type: string
      test_suite:
        description: MBridge test suite (L1 or unit-only)
        required: true
        type: string
      poll_timeout_seconds:
        description: Maximum time to wait for the downstream workflow
        required: false
        default: 12600
        type: number
    secrets:
      BOT_ID:
        required: true
      BOT_KEY:
        required: true

permissions: {{}}

jobs:
  mbridge-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    env:
      MBRIDGE_APP_ID: ${{{{ secrets.BOT_ID }}}}
      MBRIDGE_PRIVATE_KEY: ${{{{ secrets.BOT_KEY }}}}
      MBRIDGE_MCORE_REF: ${{{{ inputs.mcore_ref }}}}
      MBRIDGE_TEST_SUITE: ${{{{ inputs.test_suite }}}}
      MBRIDGE_POLL_TIMEOUT_SECONDS: ${{{{ inputs.poll_timeout_seconds }}}}
    steps:
      - name: Dispatch, monitor, and clean up MBridge validation
        shell: bash
        run: |
          python3 <<'MBRIDGE_ORCHESTRATOR'
{indented_source}
          MBRIDGE_ORCHESTRATOR
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_workflow(SOURCE_PATH.read_text(encoding="utf-8"))
    if args.check:
        existing = (
            WORKFLOW_PATH.read_text(encoding="utf-8") if WORKFLOW_PATH.exists() else ""
        )
        if existing != rendered:
            print(f"{WORKFLOW_PATH.relative_to(ROOT)} is stale; regenerate it")
            return 1
    else:
        WORKFLOW_PATH.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
