// Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

"use strict";

const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "../..");
const sourcePath = path.join(root, ".github/scripts/mbridge_orchestrator.js");
const workflowPath = path.join(
  root,
  ".github/workflows/_mbridge_orchestrator.yml",
);

function renderWorkflow(source) {
  const indentedSource = source
    .trimEnd()
    .split("\n")
    .map((line) => (line ? `          ${line}` : ""))
    .join("\n");
  return `# Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# GENERATED by .github/scripts/generate_mbridge_workflow.js.
# Edit .github/scripts/mbridge_orchestrator.js and regenerate this file.

name: Run MBridge validation

on:
  workflow_call:
    inputs:
      mcore_ref:
        description: Full Megatron-LM commit SHA tested by MBridge
        required: true
        type: string
      test_suite:
        description: MBridge test suite (L1 or unit-only)
        required: true
        type: string
      poll_timeout_seconds:
        description: Maximum time to wait for the downstream workflow
        required: false
        default: 12600
        type: number
    secrets:
      BOT_ID:
        required: true
      BOT_KEY:
        required: true

permissions: {}

jobs:
  mbridge-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    env:
      MBRIDGE_APP_ID: \${{ secrets.BOT_ID }}
      MBRIDGE_PRIVATE_KEY: \${{ secrets.BOT_KEY }}
      MBRIDGE_MCORE_REF: \${{ inputs.mcore_ref }}
      MBRIDGE_TEST_SUITE: \${{ inputs.test_suite }}
      MBRIDGE_POLL_TIMEOUT_SECONDS: \${{ inputs.poll_timeout_seconds }}
      MBRIDGE_ORCHESTRATOR_RUN: "1"
    steps:
      - name: Dispatch, monitor, and clean up MBridge validation
        shell: bash
        run: |
          node <<'MBRIDGE_ORCHESTRATOR'
${indentedSource}
          MBRIDGE_ORCHESTRATOR
`;
}

const rendered = renderWorkflow(fs.readFileSync(sourcePath, "utf8"));
if (process.argv.includes("--check")) {
  const existing = fs.existsSync(workflowPath)
    ? fs.readFileSync(workflowPath, "utf8")
    : "";
  if (existing !== rendered) {
    console.error(
      `${path.relative(root, workflowPath)} is stale; regenerate it`,
    );
    process.exitCode = 1;
  }
} else {
  fs.writeFileSync(workflowPath, rendered);
}

module.exports = { renderWorkflow };
