# Copyright (c) 2020-2021, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Build docs
on:
  workflow_call:
    inputs:
      docs_directory:
        description: "Directory where the docs will be built"
        required: false
        type: string
        default: "docs"

jobs:
  main:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Sphinx build
        run: |
          cd ${{ inputs.docs_directory }}
          uv run --only-group docs sphinx-build --fail-on-warning --builder html . _build/html

      - name: Sphinx linkcheck
        run: |
          cd ${{ inputs.docs_directory }}
          uv run --only-group docs sphinx-build --builder linkcheck . _build/linkcheck || true

      - name: Eliminate false positives
        run: |
          FALSE_POSITIVES_JSON=${{ inputs.docs_directory }}/false_positives.json
          NEEDS_REVIEW_JSON=${{ inputs.docs_directory }}/links_needing_review.json
          LINKCHECK_JSON=${{ inputs.docs_directory }}/_build/linkcheck/output.json

          function check_environment {
            local err=0
            if ! [ -x "$(command -v jq)" ]; then
              >&2 echo "jq is required but is not found."
              ((err++))
            fi
            if [ ! -f "${LINKCHECK_JSON}" ]; then
              >&2 echo "Did not find linkcheck output JSON file: ${LINKCHECK_JSON}."
              ((err++))
            fi
            if [ "${err}" -gt 0 ]; then
              exit 2
            fi
          }

          function check_links {
            local err=0
            broken=$(jq -s 'map(select(.status=="broken"))' "$LINKCHECK_JSON")
            count=$(echo "${broken}" | jq 'length')
            for i in $(seq 0 $(($count - 1)))
            do
              entry=$(echo "${broken}" | jq ".[${i}]")
              link=$(echo "${entry}" | jq -r '.uri')
              [ -n "${DEBUG}" ] && {
              echo >&2 "Checking for false positive: ${link}"
              }
              local false_positive_resp="false"
              local needs_review_resp="false"
              if [ -f "${FALSE_POSITIVES_JSON}" ]; then
                false_positive_resp=$(jq --arg check "${link}" -s 'any(.uri == $check)' < "${FALSE_POSITIVES_JSON}")
              fi
              if [ -f "${NEEDS_REVIEW_JSON}" ]; then
                needs_review_resp=$(jq --arg check "${link}" -s 'any(.uri == $check)' < "${NEEDS_REVIEW_JSON}")
              fi
              # "false" indicates that the URL did not match any of the URIs in the false positive file.
              if [[ "false" = "${false_positive_resp}" && "false" = "${needs_review_resp}" ]]; then
                ((err++))
                echo "${entry}"
              fi
            done
            exit "${err}"
          }

          check_environment
          check_links

      - name: Upload linkcheck output
        uses: actions/upload-artifact@v4
        with:
          name: linkcheck-artifact
          path: ${{ inputs.docs_directory }}/_build/linkcheck
          retention-days: 7

      - name: Upload docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: ${{ inputs.docs_directory }}/_build/html
          retention-days: 7
