# Copyright (c) 2020-2021, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
on:
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install ruff
      run: |
        pip install ruff

    - name: Run FW level ruff
      run: |
        FW_LEVEL_SELECT="F541, F841, F401, E741, F821, E266, I, D101, D103"
        FW_LEVEL_IGNORE="E501"

        echo "Ruff check is executed with Framework level select: ($FW_LEVEL_SELECT) and ignore: (FW_LEVEL_IGNORE)"

        ruff check . --verbose --select "$FW_LEVEL_SELECT" --ignore "$FW_LEVEL_IGNORE" --isolated
        ruff format --check . --verbose --select "$FW_LEVEL_SELECT" --ignore "$FW_LEVEL_IGNORE" --isolated

    - name: Run Repo level ruff
      run: |
        ruff check . --verbose
        ruff format --check . --verbose
