# Copyright (c) 2020-2021, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: "Code freeze"

on:
  workflow_call:
    inputs:
      name_of_library:
        type: string
        description: Name of Nemo library
      python_package:
        type: string
        description: Name of Python package
      type_of_release:
        type: string
        description: Type of release (major|minor|pre_release)
    outputs:
      release-branch: 
        description: "Released version (same as its branch name)"
        value: ${{ jobs.create-release-branch.outputs.version }}
      
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["ko3n1g"]'), github.actor)
    environment: 
      name: main
    outputs:
      version: ${{ steps.release-branch.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.run_id }}
          fetch-depth: 0
          ref: main

      - name: Get release branch ref
        id: release-branch
        run: |
          cd ${{ github.run_id }}
                    
          if [[ "${{ inputs.type_of_release }}" != "pre_release" ]]; then
            sed -i "/^PRE_RELEASE/c\PRE_RELEASE = ''" ${{ inputs.python_package }}/package_info.py 
          fi

          VERSION=$(python -c 'import ${{ inputs.python_package }}; print(${{ inputs.python_package }}.__version__)')
          echo "version=r$VERSION" | tee -a "$GITHUB_OUTPUT"

          echo git switch --force-create $VERSION origin/main
          echo git push -u origin $VERSION --force

  bump-next-version:
    runs-on: ubuntu-latest
    needs: [create-release-branch]
    environment: 
      name: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.run_id }}
          fetch-depth: 0
          fetch-tags: true
          ref: main

      - name: Bump version
        id: bump-version
        run: |
          cd ${{ github.run_id }}
          PRE_RELEASE=$(cat ${{ inputs.python_package }}/package_info.py | awk '/^PRE_RELEASE = /' | awk -F"= " '{print $2}' | tr -d '"' | tr -d "'")
          MAJOR=$(cat ${{ inputs.python_package }}/package_info.py | awk '/^MAJOR = /' | awk -F"= " '{print $2}')
          MINOR=$(cat ${{ inputs.python_package }}/package_info.py | awk '/^MINOR = /' | awk -F"= " '{print $2}')
          PATCH=$(cat ${{ inputs.python_package }}/package_info.py | awk '/^PATCH = /' | awk -F"= " '{print $2}')

          if [[ "${{ inputs.type_of_release }}" == "pre_release" ]]; then
            NEXT_MAJOR=$MAJOR
            NEXT_MINOR=$MINOR
            NEXT_PRE_RELEASE=rc$(( $(echo $PRE_RELEASE | awk -F"rc" '{print $2}') + 1))
          elif [[ "${{ inputs.type_of_release }}" == "major" ]]; then
            NEXT_MAJOR=$(( MAJOR + 1))
            NEXT_MINOR=0
            NEXT_PRE_RELEASE=rc0
          else
            NEXT_MAJOR=$MAJOR
            NEXT_MINOR=$(( MINOR + 1))
            NEXT_PRE_RELEASE=rc0
          fi

          sed -i "/^MAJOR/c\MAJOR = $NEXT_MAJOR" ${{ inputs.python_package }}/package_info.py
          sed -i "/^MINOR/c\MINOR = $NEXT_MINOR" ${{ inputs.python_package }}/package_info.py
          sed -i "/^PRE_RELEASE/c\PRE_RELEASE = '$NEXT_PRE_RELEASE'" ${{ inputs.python_package }}/package_info.py

          echo "version=$NEXT_MAJOR.$NEXT_MINOR.$PATCH$NEXT_PRE_RELEASE" | tee -a "$GITHUB_OUTPUT"

      - name: Create Version Bump PR
        uses: peter-evans/create-pull-request@v6
        id: create-pull-request
        with:
          path: ${{ github.run_id }}
          branch: ci/bump-${{ steps.bump-version.outputs.version }}
          title: 'Version bump to `${{ steps.bump-version.outputs.version }}`'
          body: |
            🚀 Version bump ${{ inputs.name_of_library }} to `${{ steps.bump-version.outputs.version }}`
          commit-message: "[🤖]: Howdy folks, let's bump ${{ inputs.name_of_library }} to `${{ steps.bump-version.outputs.version }}` !"
          signoff: true
          assignees: okoenig

  notify:
    runs-on: ubuntu-latest
    needs: [create-release-branch, bump-next-version]
    environment: 
      name: main
    steps:
      - name: Main
        run: |
          MESSAGE='{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "[🤖]: ${{ inputs.name_of_library }} has been frozen 🎉 to branch `${{ needs.create-release-branch.outputs.version }}`"
                }
              }
            ]
          }'

          curl -X POST -H "Content-type: application/json" --data "$MESSAGE" ${{ secrets.SLACK_RELEASE_ENDPOINT }}