name: Community Bot

on:
  workflow_call:
    inputs:
      environment:
        required: false
        description: The environment to use for the workflow
        type: string
        default: "main"
      community_project_id:
        required: true
        description: The GitHub project ID to add community issues to
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  manage-community-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    environment: ${{ inputs.environment }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Check pre-conditions
        id: pre-flight
        env:
          IS_VALID_EVENT: ${{ (github.event_name == 'issues' || github.event_name == 'issue_comment') }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          COMMENT_AUTHOR: ${{ github.event.comment.user.login || '' }}
          REPO: ${{ github.repository }}
        run: |
          # Get the username who triggered the action
          USERNAME="${{ github.actor }}"

          echo "Checking if $ISSUE_AUTHOR is a collaborator..."
          API_URL="https://api.github.com/repos/$REPO/collaborators/$ISSUE_AUTHOR"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            $API_URL)

          if [ "$STATUS" -eq 204 ]; then
            echo "is_maintainer=true" | tee -a $GITHUB_OUTPUT
          elif [ "$STATUS" -eq 404 ]; then
            echo "is_maintainer=false" | tee -a $GITHUB_OUTPUT
          else
            echo "Unexpected response: $STATUS"
            exit 1
          fi

          echo "is_valid_event=$IS_VALID_EVENT" | tee -a $GITHUB_OUTPUT

          echo "username=$USERNAME" | tee -a $GITHUB_OUTPUT

      - name: Add community-request label for community users
        if: |
          (
            steps.pre-flight.outputs.is_maintainer == 'false'
            && steps.pre-flight.outputs.is_valid_event == 'true'
          )
        run: |
          # Add the community-request label
          gh issue edit ${{ github.event.issue.number }} --add-label "community-request"

      - name: Add community issue to community project
        if: |
          (
            steps.pre-flight.outputs.is_maintainer == 'false'
            && steps.pre-flight.outputs.is_valid_event == 'true'
          )
        run: |
          # Get the issue's node ID
          ISSUE_NODE_ID=$(gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }} --jq .node_id)

          # Check if issue is already in the project
          EXISTING_ITEMS=$(gh api graphql -f query='
            query {
              node(id: "'${{ inputs.community_project_id }}'") {
                ... on ProjectV2 {
                  items(first: 100) {
                    nodes {
                      content {
                        ... on Issue {
                          id
                        }
                      }
                    }
                  }
                }
              }
            }
          ' --jq '.data.node.items.nodes[].content.id')

          if echo "$EXISTING_ITEMS" | grep -q "$ISSUE_NODE_ID"; then
            echo "Issue #${{ github.event.issue.number }} is already in project ${{ inputs.community_project_id }}, skipping"
          else
            echo "Adding issue #${{ github.event.issue.number }} to project ${{ inputs.community_project_id }}"
            gh api graphql -f query='
              mutation {
                addProjectV2Item(input: {
                  projectId: "'${{ inputs.community_project_id }}'"
                  contentId: "'$ISSUE_NODE_ID'"
                }) {
                  item {
                    id
                  }
                }
              }
            '
          fi

      - name: Remove community-request label for maintainers
        if: |
          (
            steps.pre-flight.outputs.is_maintainer == 'true'
            && steps.pre-flight.outputs.is_valid_event == 'true'
          )
        run: |
          # Check if the issue has the "community-request" label before attempting to remove it
          ISSUE_NUMBER=${{ github.event.issue.number }}
          LABELS=$(gh issue view "$ISSUE_NUMBER" --json labels -q '.labels[].name')
          if echo "$LABELS" | grep -q "^community-request$"; then
            gh issue edit "$ISSUE_NUMBER" --remove-label "community-request"
          else
            echo "Label 'community-request' not present on issue #$ISSUE_NUMBER, skipping removal."
          fi

      - name: Log action taken
        run: |
          echo "User: ${{ steps.pre-flight.outputs.username }}"
          echo "Is maintainer: ${{ steps.pre-flight.outputs.is_maintainer }}"
          echo "Event: ${{ github.event_name }}"
          echo "Issue number: ${{ github.event.issue.number }}"
