name: Community Bot

on:
  issues:
    types: [opened, edited, reopened, closed, deleted]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  community-bot:
    uses: ./.github/workflows/_community_bot.yml
    with:
      maintainers: ko3n1g
