name: Community Bot

on:
  issues:
    types: [opened, edited, reopened, closed, deleted]
  issue_comment:
    types: [created, edited, deleted]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  community-bot:
    uses: ./.github/workflows/_community_bot.yml
    with:
      community_project_id: ${{ vars.COMMUNITY_PROJECT_ID }}
      app-id: ${{ vars.BOT_ID }}
    secrets:
      BOT_KEY: ${{ secrets.BOT_KEY }}
