name: Community Bot

on:
  issues:
    types: [opened, edited, reopened, closed, deleted]
  issue_comment:
    types: [created, edited, deleted]
  push:

jobs:
  community-bot:
    uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_community_bot.yml@80b7b4e0e155df133be76073435bf7d014fc6302
    with:
      issue_number: 203
      issue_author: chtruong814
      community_project_id: 16
    secrets:
      GH_TOKEN: ${{ secrets.PAT }}
